greenplanetmart:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "/Users/simonschork/Library/CloudStorage/OneDrive-Persönlich/10 Projects/Master Business Intelligence/10 Data Modeling and Reporting/GreenPlanetMart_Project/project_implementation/warehouse/greenplanetmart.duckdb"
      threads: 4
