greenplanetmart:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/simonschork/Documents/GreenPlanetMart_Project/project_implementation/warehouse/greenplanetmart.duckdb
      threads: 4
